#!/bin/sh

path="$(cd $OUTDIR && mktemp parts/$MESSAGE_ID.XXXXXXXXXX)"

# save the input
cat > "$OUTDIR/$path"

ftype="$(file "$OUTDIR/$path")"
echo "<li><a href='/$path'>${ftype#*:}</a></li>" >> parts.html
exit 0
