.\" gmimport.1 was written by Omar Polo <op@openbsd.org> and is placed in
.\" the public domain.  The author hereby disclaims copyright to this
.\" source code.
.Dd May 5, 2023
.Dt GMIMPORT 1
.Os
.Sh NAME
.Nm gmimport
.Nd import emails into a sqlite database
.Sh SYNOPSIS
.Nm
.Ar dbpath
.Sh DESCRIPTION
.Nm
reads a sequence of path to emails from standard inputs and inserts them
into the
.Xr msearchd 8
sqlite3 database at
.Ar dbpath .
.Sh EXAMPLES
To index all the messages in the
.Pa ~/Mail/gotmarc
maildir, useful to initially populate the database:
.Pp
.Dl mlist ~/Mail/gotmarc | gmimport /var/www/msearchd/mails.sqlite3
.Pp
Incorporate new messages in the maildir and add them to the database,
useful after fetching new mails:
.Pp
.Dl minc ~/Mail/gotmarc | gmimport /var/www/msearchd/mails.sqlite3
.Sh SEE ALSO
.Xr minc 1 ,
.Xr mlist 1 ,
.Xr msearchd 8
.Sh BUGS
.Nm
doesn't detect the insert of duplicate messages.
Should that happen, the database needs to be recreated.
