#!/bin/sh
#
# gotmarc was written by Omar Polo <op@openbsd.org> and is placed in the
# public domain.  The author hereby disclaims copyright to this source
# code.

progname="$(basename "$0")"
usage() {
	echo "usage: $progname [-c csumdir] [-j n] [-m maildir] [-o outdir]" >&2
	exit 1
}

libexec=.
mblaze=.mblaze

csumdir=$HOME/.cache/gotmarc/threadsum
mdir=$HOME/Mail/gameoftrees
outdir=/var/www/marc

while getopts c:j:m:o: flag; do
	case $flag in
	c) csumdir="$OPTARG" ;;
	j) MAKE_JOBS="$OPTARG" ;;
	m) mdir="$OPTARG" ;;
	o) outdir="$OPTARG" ;;
	?) usage ;;
	esac
done

# set up the env
export CSUMDIR="$csumdir"
export MAKE_JOBS="${MAKE_JOBS:-1}"
export MBLAZE="$mblaze"
export MBLAZE_PAGER=cat
export MDIR="$mdir"
export OUTDIR="${OUTDIR:-/var/www/marc}"

# make sure the directories are there
set -e
mkdir -p "$csumdir"
mkdir -p "$outdir/mail"
mkdir -p "$outdir/parts"
mkdir -p "$outdir/text"
mkdir -p "$outdir/thread"
set +e

export PATH="$libexec:$PATH"

fmt='%i-%R %16D<%64f>%128S'
mlist "${MDIR}" | mthread -r | mscan -f "$fmt" | pe | mkindex
